### ISSUE TITLE
Reel.js unable to find image dimensions, when it does, screen jumps back to top on scroll

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#13]
This is two issues: 
1. On [http://sketchbook.nclud.com/created/beercamp/](http://sketchbook.nclud.com/created/beercamp/), I'm seeing errors with reel.js more often than not. I'm wondering if this might be related to images not being loaded all the way since we're in a production environment that's a bit slower than localhost. If I soft refresh a few times, I can sometimes get it working. In my mind, this is because page assets are cached in the browser and loading faster.
2. When the scripts load as expected, it seems that scrolling past the header area causes jumpy behavior. I haven't been able to tell if this is a timing issue (related to a `setTimeout`, a scrolling issue, or something else.

**Comment by kyleconrad** [comment]
The reel.js errors seem strange - on localhost it's all good, but I also haven't seen any issues on the browserspring.com hosted version (http://www.browserspring.com/sketchbook/beercamp.html) - it seems to load all the images and all without any errors?
