### ISSUE TITLE
Get rid of all Ruby dependencies

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#24]
Maybe we can scrap all ruby in this project so anyone can work on it without going through dependency hell. This would be a bit of a task but it could be fun.

**Comment by jshawl** [comment]
+1 I keep running into

```
Warning: Command failed: /Library/Ruby/Gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in `materialize': Could not find csscss-1.3.2 in any of the sources (Bundler::GemNotFound)
```

Though I'm not sure what's removable without more setup documentation (https://github.com/nclud/sketchbook/pull/26)

**Comment by imjared** [comment]
can safely say idgaf about ruby dependencies anymore
