### ISSUE TITLE
"Excerpts" for posts

### ISSUE THREAD

**Issue by kyleconrad** [nclud/sketchbook#28]
Is there a way to pull an excerpt (or manually enter one) for posts? On the static design (http://www.browserspring.com/sketchbook/) the goal was to have the first two or three sentences as an excerpt showing up on the front/archive pages beneath the post title for some context.

**Comment by jshawl** [comment]
This can be done either automatically, like: https://github.com/jshawl/jesse.sh/blob/872f9a9afea60d7abe6c9eb97c881d3e03f257b5/awl/index.html#L13-18

Where all the content up until `<!-- more -->` is shown on a given page.

Alternatively, there is front matter in place for a summary. At the top of an post, add "summary: whatever" to the front matter.

**Comment by kyleconrad** [comment]
Summary in the front matter should work well since it allows us to provide a slightly different excerpt than just adding the "more," so let's leave that in place for now. Just need to remind authors to add it in when writing the markdown file.
