### ISSUE TITLE
Users should not be able to scroll horizontally

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#3]
You may want to test this against your local but I think this is untouched from the initial repo.

When viewing on my laptop and using the trackpad to scroll, I can scroll to the right to reveal black space. We should track down why this is happening and fix the behavior so users can only scroll vertically.

![screen shot 2013-11-15 at 11 38 53 am](https://f.cloud.github.com/assets/525011/1551463/ac8d49f8-4e14-11e3-8119-0b55f9307bba.png)

Let me know if this is something I broke and I'll figure out a fix.

**Comment by kyleconrad** [comment]
Just pushed a fix - adding overflow-x: hidden to #skrollr-body

**Comment by imjared** [comment]
This seems to have created another issue of a double scrollbar in chrome

![screen shot 2013-11-15 at 12 49 54 pm](https://f.cloud.github.com/assets/525011/1552067/6ccc42e2-4e1e-11e3-9820-4705bdcd9aa0.png)
