### ISSUE TITLE
Author management

### ISSUE THREAD

**Issue by kyleconrad** [nclud/sketchbook#30]
So we don't lose visibility, need to add some sort of author management system. nclud is the base author right now, but need to be able to add new authors and assign them to posts (i.e. the latest post should be attributed to Kerry Gunther, not nclud).

**Comment by jshawl** [comment]
I know of this file: https://github.com/nclud/sketchbook/blob/230e200444bc0676c92f7cda77e61fb5d8f762f8/app/_data/authors.yml

but I'm not sure how to load that data based on an `author` in the front matter. maybe something like

```
---
layout: post
title: "The Title"
author: jared laser
---
```

And then in the post layout (https://github.com/nclud/sketchbook/blob/230e200444bc0676c92f7cda77e61fb5d8f762f8/app/_layouts/post.html) We could pull in that data.

Thoughts?

**Comment by imjared** [comment]
I think we can load up `config.yml` with authors that are manually as-needed. We can front load this with people who are likely going to be authoring content.

ex.

```
- authors
    - kerry
        - picture: foo.jpg
        - twitter: kerrygunther
    - jesse
        - picture: bar.jpg
        - twitter: jshawl
```

We can then access them with `site.authors` or something like that. We can also add these authors to the [Prose configuration] to get a dropdown menu (https://github.com/prose/prose/wiki/Prose-Configuration#select--multiselect) until I [figure out an automatic way to handle it](http://stackoverflow.com/questions/20430629/reference-config-yml-for-prose-io-options). We just need to make sure that the Prose configuration value is identical to the key for the author.

Ex:

```
options:
  - name: 'Kerry Gunther'
    value: ''kerry"
```

**Comment by jshawl** [comment]
fixed with https://github.com/nclud/sketchbook/commit/41862593e28ede0a7393e415a7d2d30c35c063a0
