### ISSUE TITLE
Separating JS files

### ISSUE THREAD

**Issue by kyleconrad** [nclud/sketchbook#34]
Moving forward, we probably want to split the JS files - right now beercamp.js contains all the Beercamp specific stuff as well as the skrollr initiation. As we move on to other case studies, probably want to pull out the skrollr and anything initiated by imagesloaded into a third JS file, just so that way we'll be able keep adding case study javascript without moving things around every time.

**Comment by jshawl** [comment]
Agreed. I think we should do this for page-specific CSS as well.

I'm currently importing into the main style [here](https://github.com/nclud/sketchbook/blob/b308dea8fa246a5c8eb2940357a64fac93cdb288/app/_scss/screen.scss#L26), but this means my CSS will cascade into someone else's page/post if their classes share the same name.

If everything is imported and minified into the same file, we'll have to namespace page-specific code, _and_ download unnecessary assets for unrelated pages. 

I'm totally into minimizing http requests, but maybe there can be a sitewide (css|js) file, and then the option to have page-specific assets.

**Comment by kyleconrad** [comment]
Closed with commit 2952713a68
