### ISSUE TITLE
infinite yellow scroll before dom loads

### ISSUE THREAD

**Issue by jshawl** [nclud/sketchbook#39]
if you start scrolling before the document.ready event fires, the yellow area at the top continues on forever (I think).

**Comment by kyleconrad** [comment]
Yeah, had this same problem with the Beercamp one, I think it's related to skrollr.js and it's strange determination of page sizes. More than welcome to suggestions on how to fix, as we struggled with it before without a solution.

**Comment by jshawl** [comment]
ya, now I'm getting infinite main top part even after waiting for the dom to load. do you know where the top part is being sized? ??https://github.com/nclud/sketchbook/blob/223289e96b440bfa59c7fd8513ceb6594ee65ac1/app/_scss/base/_header.scss#L22 ?

**Comment by kyleconrad** [comment]
Yup, that's the sizing for it.

**Comment by jshawl** [comment]
fixed with https://github.com/nclud/sketchbook/commit/d638a67387e30d81cc84f94d0404547dd163643e
