### ISSUE TITLE
missing comments

### ISSUE THREAD

**Issue by gunthek** [nclud/sketchbook#41]
the comments module appears to exist in some live posts, but not staging posts.

here it is: http://sketchbook.nclud.com/joe-corbett/

here it is not: http://staging.sketchbook.nclud.com/joe-corbett/

**Comment by jshawl** [comment]
fixed with 7f70fddfe4c902b80f7dc48818ba8c3c90348c06

http://staging.sketchbook.nclud.com/joe-corbett/
