### ISSUE TITLE
Video quality in Firefox

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#5]
Maybe we need a higher res video? Looks pretty rough in firefox on larger screens (see full)

![screen shot 2013-11-15 at 12 01 58 pm](https://f.cloud.github.com/assets/525011/1551669/c0989666-4e17-11e3-9091-d008add47c17.png)

**Comment by kyleconrad** [comment]
Just pushed a new video encoded at a higher resolution - about the best quality I can get at any sort of reasonable size with the crap that is OGG video

**Comment by imjared** [comment]
Are we limited to OGG? Would another encoding help or do we just end up bloating the filesize for no real benefit?

**Comment by kyleconrad** [comment]
Actually, it seems FF now supports WebM (which I already had in there) - just pushed the removal of OGV

**Comment by imjared** [comment]
oh hot damn. closed by e736fa3
