### ISSUE TITLE
Border on Mario section broken from container in FF25

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#6]
This seems more reproducible than not but it looks like the border is separated from the Mario container.

![screen shot 2013-11-15 at 1 00 10 pm](https://f.cloud.github.com/assets/525011/1552169/0dd3074c-4e20-11e3-9467-7255f6857577.png)

**Comment by kyleconrad** [comment]
What browser? Not currently seeing it in Chrome or Firefox -

**Comment by imjared** [comment]
I'm getting it intermittently only in FF25

**Comment by kyleconrad** [comment]
Seeing it on random resolutions as well - from the breaks in the white lines, it looks like FF is trying to vertically repeat the background-image (as opposed to restricting it to repeat-x), not sure why.

**Comment by kyleconrad** [comment]
Changed from an SVG to a PNG and it works correctly in FF - seems like an overall FF bug with SVGs as background-image elements
