### ISSUE TITLE
Animation issues by browser

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#7]
Animation performance on the Beercamp case study is inconsistent across browsers.

By browser:
- [ ] Chrome 31: general laggy animations when using a large screen resolution. I'm on a 27" monitor or something and using a smaller screen helps the issue significantly. The issue seems mostly contained to the portion using reel.js. The timeline while scrolling shows a framerate well under 30fps for the majority of the animation.
- [ ] Firefox 27 is  fairly choppy while scrolling even on 15" monitor. Pain points are the header and the reel.js portion.
- [ ] Safari 7: the drawing animation platform and the hovering layers jump during scroll. Issue is not resolved by using a smaller screen.

This may be partially due to my older hardware but I think we can probably work on some specific pain-points to smooth out these animations.

**Comment by kyleconrad** [comment]
Chrome - Reel "framerate" is determined by number of pixels scrolled, so might just need to adjust that for large monitors.

Firefox - having similar issues with the header (on mousewheel and manually scrolling). Not sure the best way to make this better as Skrollr should be "handling" the transitions.

Safari - hm. Seems another Skrollr issue that we might have to delve into, Safari seems to be scrolling things differently or not firing the transitions enough. Like it's only firing a "scroll" event every 30 pixels as opposed to every pixel.

**Comment by kyleconrad** [comment]
A note for myself to take a look at (and a possible solution):
- on desktops, don't add data attributes for scrolling to #design, just inject data attributes that trigger a before/during/after class that positions it fixed and then absolute. Won't recalculate top position that way and should still scroll reel using curTop via Skrollr.
- on mobile, inject data attributes as we are currently as that is working to successfully and smoothly scroll and fire the reel

**Comment by kyleconrad** [comment]
Should've fixed the design section scrolling on desktop (especially the jumpiness on Safari by removing directly referencing pixels and just setting fixed positioning.

Have to test on tablet still but hadn't changed anything on that front so should still work (using conditional statements to apply only to desktop).
