### ISSUE TITLE
Modularize Sass files

### ISSUE THREAD

**Issue by imjared** [nclud/sketchbook#8]
We should look for a way to DRY up the Sass a bit. Instead of requiring `style.scss` in multiple files, can we create a `common.scss` (or similar) module that would hold the site's main styles like the type, grid, etc. This would have `front.scss`,  `post.scss`, and `syntax.scss` baked into it.

We can then, on a per-**page** basis create `beercamp.scss` or `page.scss` as-needed as an addendum to `common.scss`. We can either test or just do whatever is easier between
- per-page download a `[pagename].scss` that is a result of concatenating and minifying `common.scss` + `page.scss`.
- on individual pages just insert `[pagename].scss` minified, not concatenated with `common.scss`. This is an extra http request but smaller file size than if we went with the other option.

open to other suggestions too

**Comment by kyleconrad** [comment]
Whichever way you think is best, I can work with it - I think the second way sounds reasonable so that common.scss will get cached across the board, leading people to only download the minified secondary file.

**Comment by imjared** [comment]
Agreed. It'll help me out on the Jekyll side of things too.
